config/routes.rb
IdeasApp::Application.routes.draw do
  resources :ideas

  

end

app/models/idea.rb
class Idea < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
  end

  def create
    @idea = Idea.create(params[:idea].permit(:title))
  end
  
  def edit
    # Find the record by id
    @idea = Idea.find(params[:id])
    # Change the attribute to done
    @idea.done = true
    # Save it back to the database
    # (the change only existed in Ruby code before this)
    @idea.save
  end

  def destroy
    # Find the record by id
    @idea = Idea.find(params[:id])
    # Destroy & save it
    @idea.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/create.html.erb
<h2>You just got an idea "<%= @idea.title %>"</h2>

<%= link_to "Back to ideas list", ideas_path %>

app/views/ideas/destroy.html.erb
<h2>Fearless destruction for "<%= @idea.title %>"</h2>

<%= link_to "Back to ideas list", ideas_path %>

app/views/ideas/edit.html.erb
<h2>You are the man cause you've done "<%= @idea.title %>"</h2>

<%= link_to "Back to ideas list", ideas_path %>

app/views/ideas/index.html.erb
<h1>Ideas!</h1>
<ol>
	<% @ideas.each do |idea| %>
		<li>
			<%= idea.title %>
			<% if idea.done %>
				X
        <%= link_to "remove", idea_path(idea), method: :delete %>
			<% else %>
				<%= link_to "O", edit_idea_path(idea) %>
			<% end %>
		</li>
	<% end %>
</ol>

<%= form_for :idea do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %> 
  <%= form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>